# model_name: TransformerRecon  # choose from NIERT, TransformerRecon
model_name: NIERT  # choose from NIERT, TransformerRecon
# model_name: TransformerRecon  # choose from NIERT, TransformerRecon

resume_from_checkpoint: 

dataset_type: TFR_FINETUNE
# dataset_type: TFR
# dataset_type: Mathit

# dataset path
data_root: dataset path of ADlet
cfg_dim_input: 3
cfg_dim_output:

# train/val set
train_path: train/train_val.txt

# test set
## choose the test set: test_0.txt, test_1.txt, test_2.txt, test_3.txt,test_4.txt,test_5.txt,test_6.txt
test_path: test/test_0.txt

batch_size: 5
# batch_size: 32
max_epochs: 100
# lr: 0.0001
# lr_decay: 0.99
lr: 0.0005
lr_decay: 0.97

model_arch_cfg:
  layers: 2
  dim_hidden: 128
  dim_inner: 512
  num_heads: 4


# which gpu to use
gpu: 1 # 0 cpu, 1 gpu:0, 2 gpu:1
val_check_interval: 1.0

# num_workers in dataloader
num_workers: 4

# preprocessing of data
## input & output
mean_heat: 298
std_heat: 50
